#!/bin/bash
# Bash completion for voice-mode command (using Click-generated completions)
# Source this file to enable completion for voice-mode
#
# This script integrates with Click's built-in shell completion system
# while maintaining compatibility with metool's sourcing pattern.
#
# Usage:
#   Source directly:  source ~/.voicemode/shell/completions/voice-mode.bash
#   Via metool:       Automatically sourced when package is installed
#
# The script checks if voice-mode is available and uses Click's completion
# generation, falling back gracefully if the command is not found.

# Check if voice-mode command exists
if command -v voice-mode &> /dev/null; then
    # Use Click's built-in completion generation
    # This evaluates the completion script generated by Click
    eval "$(_VOICE_MODE_COMPLETE=bash_source voice-mode 2>/dev/null)"
    
    # If eval succeeded, we're done
    if [ $? -eq 0 ]; then
        return 0 2>/dev/null || :
    fi
fi

# Fallback message if voice-mode is not installed or completion failed
if [ -t 1 ]; then  # Only show message if running interactively
    echo "# voice-mode completion: Command not found or completion generation failed" >&2
    echo "# Install voice-mode with: uvx --refresh voice-mode" >&2
    echo "# Or for development: pip install -e /path/to/voicemode" >&2
fi

# Return success to avoid breaking shell initialization
return 0 2>/dev/null || :